### ISSUE TITLE
UnauthorizedAccessException on trying to access directories within the workspace

### ISSUE THREAD

**Issue by naveensrinivasan** [lukebuehler/CShell#9]
If a user does not have permission within one of the directories within the Workspace root folder then it throws an unauthorizedaccessexception.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
   at CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren() in c:\n\CShell\Src\CShell\Modules\Workspace\ViewModels\FolderViewModel.cs:line 84
   at CShell.Modules.Workspace.ViewModels.FolderViewModel.get_Children() in c:\n\CShell\Src\CShell\Modules\Workspace\ViewModels\FolderViewModel.cs:line 74

**Comment by lukebuehler** [comment]
fixed in #10
